### ISSUE TITLE
[FEATURE REQUEST] Installation instructions of `luasocket` on Windows w/o Lua installation

### ISSUE THREAD

**Issue by emk2203** [open-dynaMIX/simple-mpv-webui#11]
If you want to run this on Windows, it is difficult to see where to get `luasocket` and where to put it on a minimal Windows install (HTPC) with `mpv` only, not a full Lua install.

It would be helpful to point the procedure out in the instructions. This would also broaden the user range to Windows users.

**Comment by rofrol** [comment]
I have this https://github.com/rofrol/elm-mpv-webui/blob/master/README.md#lua instruction for Ubuntu. Maybe this will help you.

**Comment by open-dynaMIX** [comment]
@emk2203 It would be great to have some documentation about that.

I don't use any Windows systems (didn't even know it works under Windows). If you could provide the necessary steps (or even better, make a PR), that would be great!

**Comment by emk2203** [comment]
I'll give it a try, but I am more a Linux guy myself, the only significant windows usage is on this HTPC, with Windows for historical reasons. So, if anyone else can step up to the challenge, I would be more than happy.

**Comment by chuck-** [comment]
I confirm it works under Windows.
You need to:

1. build **luajit** (latest stable version, currently 2.0.5).
2. place **luajit-\<version\>/src/lua51.dll** in the same folder as mpv
3. build **luasocket** (easier with the help of luarocks) or download binaries somewhere (I've seen many releases, search on luapower)
4. place **socket/core.dll** and **mime/core.dll**, **lua/{socket,*.lua}** inside mpv folder
5. install (and configure) this script
6. profit

I admit it is a nuisance having to pass through the whole process (especially on Windows), so perhaps it's better to distribute the binaries.
Both luajit and luasocket are distributed with MIT license, so there should not be any problem doing so.

**Comment by open-dynaMIX** [comment]
@chuck- Awesome, thanks a lot! I have included a link to your repo in the README.

**Comment by chuck-** [comment]
You're welcome, glad to have been of help!
