### ISSUE TITLE
Knocks off other HTTP stream whenever interface sends a GET request?

### ISSUE THREAD

**Issue by lazerfloyd** [open-dynaMIX/simple-mpv-webui#242]
Hi!

Really love the interface, however I've run into a strange issue. Please bear with me, as it's a little esoteric: 

I currently have VLC serving a FLAC stream of my HTPC's audio over HTTP. Everything I play with MPV by itself plays fine over HTTP/FLAC with no issues. However, if I drop simple-mpv-webui in there and start MPV up, the audio starts to play as usual, but the HTTP stream will get knocked off the client (e.g. the stream closes and has to be manually reconnected) every time the webui interface sends MPV a GET request to refresh the UI. This seems entirely localized to the HTTP stream, as MPV and the audio media continue to play fine over the HTPC's hardware connection while all this is happening. 

I should also mention that the HTTP stream and simple-mpv-webui run on different ports, so I've eliminated that as a possible error source. I've spent the better part of this afternoon pinning this issue down, so I'm fairly confident it's a real thing, but I'm at a loss as to what logs/info would be required to isolate and fix this. Please let me know and I will gladly gather whatever's necessary.

Thanks!

**Comment by open-dynaMIX** [comment]
Hi @lazerfloyd

That's a strange issue. Let's see if we can get to the bottom of this.

I don't fully understand your setup and what's failing. You have VLC as server on one host and play the stream with MPV on another host, correct? And if you start MPV with the webui, what exactly stops working?

> This seems entirely localized to the HTTP stream, as MPV and the audio media continue to play fine over the HTPC's hardware connection while all this is happening.

So MPV continues to play the audio. Sorry, I really don't understand what's broken then.

Additionally it would help to know what OS the host with the webui has running.

## Attempt to reproduce

I've installed VLC on host A (Ubuntu) and configured it to stream a file over HTTP/FLAC on `:8080/`. I've started MPV with the webui on host B (Arch Linux) and played the stream from VLC. The webui was served on port 8080 from host B (there is no reason to use different ports, because it's different hosts). I've fired up a browser on host C (Android) and opened the webui. Everything was working just fine.
This was all in the LAN, using the hosts internal IPv4 addresses.

**Comment by lazerfloyd** [comment]
Right, sorry, that wasn't super clear. Here's a more detailed description of my setup:

Host A is running Lubuntu 20.04 and Host B in this case is an Android phone running the latest versions of VLC and Chrome.

Host A is running a VLC instance that connects to PulseAudio and streams "Monitor of Built-in Analog Out" over HTTP/FLAC on :8020. Then MPV is run on Host A and plays whatever (in this case, cdda from /dev/sr0). The audio plays out the hardware audio jack while also being encoded as a FLAC stream simultaneously. MPV runs webui over port :8080.

Host B is connected locally to the HTTP/FLAC stream over :8020 and to webui through Chrome at :8080. The stream plays fine at first and I can control the playback with no issues, but the stream keeps crashing on Host B a few seconds in and needs a manual reconnect, which seems to happen whenever webui tries to update the progress bar (I can see it pop up as a GET request on Host A when I turn on logging in MPV). 

While all this is happening, MPV is still playing fine on Host A - no underruns or skips or anything, and as I said, the audio coming out of the hardware jack is undisturbed. VLC on Host A doesn't crash or show any errors - as far as its concerned, the FLAC stream is never interrupted. This seems to be an HTTP connection issue.

If I run MPV without webui, or if I run a second VLC instance to play the same content instead of MPV and connect to its webui module instead (also configured to go over :8080) the stream remains stable on Host B.

I'm wondering if there's something that's not playing nice with HTTP traffic running on concurrent ports - maybe it's an issue with LuaSockets itself? I'm just spitballing, it's probably not super helpful. Anyway, thanks for taking the time with this. I understand if you decide to call this one "out of scope." :)

**Comment by open-dynaMIX** [comment]
Ah, now I understand! I was able to reproduce this and I now know what's happening: Whenever the webui detects that MPV is playing, it plays a [silent mp3](https://github.com/open-dynaMIX/simple-mpv-webui/blob/master/webui-page/static/audio/silence.mp3) in a loop to make the [notifications](https://github.com/open-dynaMIX/simple-mpv-webui#media-session-api) work. So I assume whenever the browser starts playing the silent mp3, vlc gets paused.

I will have to see if I can find a more elegant way to handle this or at least make it possible to disable that feature. In the meantime, you can make it work with following quick and dirty patch:

```diff
diff --git a/webui-page/index.html b/webui-page/index.html
index 7973cc2..359e049 100644
--- a/webui-page/index.html
+++ b/webui-page/index.html
@@ -217,7 +217,7 @@
       </div>
     </div>
 
-    <audio id="audio" src="static/audio/silence.mp3" loop></audio>
+    <!--<audio id="audio" src="static/audio/silence.mp3" loop></audio>-->
 
   </body>
   <script src="webui.js"></script>
diff --git a/webui-page/webui.js b/webui-page/webui.js
index 79e515f..ab65305 100644
--- a/webui-page/webui.js
+++ b/webui-page/webui.js
@@ -536,14 +536,14 @@ function setPlayPause(value) {
       div.innerHTML = '<i class="fas fa-play"></i>';
     });
     if ('mediaSession' in navigator) {
-      audioPause();
+      // audioPause();
     }
   } else {
     [].slice.call(playPause).forEach(function (div) {
       div.innerHTML = '<i class="fas fa-pause"></i>';
     });
     if ('mediaSession' in navigator) {
-      audioPlay();
+      // audioPlay();
     }
   }
 }
@@ -667,7 +667,7 @@ function status(){
 function audioLoad() {
   if (!window.loaded) {
     DEBUG && console.log('Loading dummy audio');
-    document.getElementById("audio").load();
+    // document.getElementById("audio").load();
     window.loaded = true;
   }
 }
```

Hope that helps!

**Comment by lazerfloyd** [comment]
OMG, thank you! That indeed completely fixed it. Hopefully there is another way to restore that functionality down the road that doesn't necessitate that workaround, as I rather liked the notifications, I must say.

Anywho, thanks again!

**Comment by open-dynaMIX** [comment]
Awesome!

Unfortunately AFAIK there is no other way to work around that as of yet (at least for Chrome on Android).

> [Chrome for Android requests "full" audio focus to show media notifications only when the media file duration is at least 5 seconds.](https://developers.google.com/web/updates/2017/02/media-session#implementation_notes)

I think the best we can do is let the clients decide if the media session api should be used. This choice could be saved in a cookie, so it is remembered per client.
