### ISSUE TITLE
FR - Show mpv-start-options in the WebUI

### ISSUE THREAD

**Issue by francwalter** [open-dynaMIX/simple-mpv-webui#331]
Hallo

I use mpv to show movies to my children, but not too long, only some few minutes, e.g. old Disney Cartoons.
I start the movies (full play time about 3 hours) from a start time to an end time with the options --start= and --end=
To show the end option, and to know when the kids movie-time will be over, I write the end time additionaly to the screen, with e.g.: --osg-msg1="Ende: 7:24", so I can see, how many time left (e.g. by pressing "o" to see the actual time tag).

Now I found this great tool here, simple-mpv-webui, which is a good help already, I can see on my phone (without need to stay in the movie-room), at what time the movie is. 
But I have to remember the end-time, it is not to find in the WebUI page. 

Could it be done theoretically that the webui.lua hands over the mpv-options (--start and --end) to the WebUI?
Or is that beyond the scope of the capabilities of lua scripts?
I don't know if Lua can get grip of that.

Thanks for hints.
frank

EDIT: I found this documentation: [LUA SCRIPTING](https://github.com/mpv-player/mpv/blob/master/DOCS/man/lua.rst#lua-scripting) about it, but it would take hours for me to understand it 😢

**Comment by francwalter** [comment]
Perfect!!! Thank a lot!
I immediately used it in a little Tasker Action (Tasker is an automation app for android, where I can put http requests and so on).
Works like charming 😄 
Thanks!

**Comment by francwalter** [comment]
I will now create some homescreen buttons with Tasker for Android to start, pause and so on.
Or a complete scene with my important functions using the api.
Great work this is!
It should be called mpv-web-ui and not "simple-..." 
Vice versa to the other repo ;)

**Comment by open-dynaMIX** [comment]
> It should be called mpv-web-ui and not "simple-..."

:grin: 

I'd like to keep this open for now, until it's integrated in the UI and merged into the main branch.

**Comment by francwalter** [comment]
Why is "end"  set in status request to "null"  if not set as parameter?
"start"  is just not present in the status request but "end" is there as "null"  if both are not set in parameter or option.
That makes it more difficult to program in Tasker.
Before, both were "none" when unset. 

I can check in Tasker if a option is not existing (unset) but if one is not existing and the other is "null" for the same thing, it is irritating.

Here is a status request answer when both are missing:

{"filename":"Donald Duck, Mickey Mouse, Pluto and Goofy Cartoon Compilation.mp4","audio-devices":[{"active":true,"name":"auto","description":"Autoselect device"},{"active":false,"name":"wasapi/{4ea0ac99-69a7-4ac7-b9fa-b002818a07b2}","description":"Lautsprecher/Kopfhörer (Realtek High Definition Audio)"},{"active":false,"name":"openal","description":"Default (openal)"},{"active":false,"name":"sdl","description":"Default (sdl)"}],"chapter-list":[],"audio-delay":0,"speed":1,"sub-delay":0,"volume-max":130,"metadata":{"minor_version":"0","major_brand":"mp42","creation_time":"2019-05-27T16:29:36.000000Z","compatible_brands":"isommp42"},"start":"212.4","track-list":[{"id":1,"dependent":false,"demux-w":640,"codec":"h264","src-id":1,"decoder-desc":"h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)","external":false,"demux-fps":25,"forced":false,"hearing-impaired":false,"demux-h":360,"main-selection":0,"albumart":false,"selected":true,"type":"video","visual-impaired":false,"ff-index":0,"default":true},{"id":1,"dependent":false,"demux-bitrate":96000,"codec":"aac","src-id":2,"decoder-desc":"aac (AAC (Advanced Audio Coding))","external":false,"demux-samplerate":44100,"demux-channels":"unknown2","demux-channel-count":2,"forced":false,"hearing-impaired":false,"audio-channels":2,"main-selection":0,"albumart":false,"selected":true,"type":"audio","visual-impaired":false,"ff-index":1,"default":true}],"playlist":[{"filename":"C:\\Users\\f\\Desktop\\Filme\\Walt Disney\\Donald Duck u.a. (Cartoon Compilation)\\Donald Duck, Mickey Mouse, Pluto and Goofy Cartoon Compilation.mp4","id":1,"playing":true,"current":true}],"duration":14214.002000,"pause":false,"chapter":0,"webui-version":"2.2.0","loop-file":false,"remaining":13726.082000,"position":487.920000,"fullscreen":true,"loop-playlist":false,"volume":130,"end":null,"chapters":0}

I started the movie without options here.

**Comment by open-dynaMIX** [comment]
Yeah exactly, `save-position-on-quit` will set the `start` property. I didn't like the `none` string and prefer to use `null`.

So all is working for you now, right?

**Comment by francwalter** [comment]
Yes, perfect.
My next project is to start mpv with ssh and include all that commands in one spot (Tasker). Also the open files commands.
Thanks!
