### ISSUE TITLE
script-opts: unknown key audio-devices, ignoring

### ISSUE THREAD

**Issue by maksymsan** [open-dynaMIX/simple-mpv-webui#36]
This is about the released version 0.3.1.
I put to mpv.conf the following setting:
script-opts=webui-audio-devices=pulse/combined pulse/alsa_output.pci-0000_00_01.1.hdmi-stereo pulse/alsa_output.pci-0000_00_14.2.analog-stereo

When mpv starts, the console shows the following:
[webui] script-opts: unknown key audio-devices, ignoring 

So, the provided list doesn't have any effect.
Changing "webui-audio-devices" to "webui-audio_devices" fixes the problem, but the documentation says about "audio-devices".
The code should reflect the documentation.

**Comment by open-dynaMIX** [comment]
Thanks for reporting this @maksymsan . That was a mismatch between docs and code. It's now fixed in the README.

**Comment by maksymsan** [comment]
audio-devices (string)
Should this be fixed in the documentation as well?

**Comment by open-dynaMIX** [comment]
@maksymsan Indeed, I forgot to also fix the title. It's done now. Thank you!
