### ISSUE TITLE
Audio devices are not cycled when audio-devices setting is missing

### ISSUE THREAD

**Issue by maksymsan** [open-dynaMIX/simple-mpv-webui#37]
This is about the release 0.3.1.
Let's not use audio-devices option in the command line or in the configuration. The documentation says "By default it uses all interfaces MPV knows of."

But in fact there is a problem with the default.

When mpv starts, no problems are reported. But when I press "Audio device" in the web interface, the following error is reported in the console:
[ao] Audio output 123456789101112131415161718 not found!
[ao] Failed to initialize audio driver '123456789101112131415161718'
Could not open/initialize audio device -> no sound.

I have a list of auto, pulse, alsa, jack and sdl audio devices according to "mpv --audio-device=help". But the mentioned above device is not present in the list.

Further attempts to press "Audio device" have no effect.

Expected result: all available to MPV audio devices should be cycled when I press "Audio device".

**Comment by open-dynaMIX** [comment]
Sorry, I referenced the wrong issue in 3ffbedc , accidentally closing this issue.

**Comment by open-dynaMIX** [comment]
Thanks for reporting this @maksymsan . It should be fixed in current master.
