### ISSUE TITLE
please give that webui.conf file

### ISSUE THREAD

**Issue by SonaliBendre** [open-dynaMIX/simple-mpv-webui#384]

**Comment by open-dynaMIX** [comment]
Hey @SonaliBendre 

I don't know what `webui.conf` you mean. Could you clarify?

Settings for the webui can be set in the mpv config or on the command line.

**Comment by SonaliBendre** [comment]
I mean this thing https://github.com/marzzzello/mpv_thumbnail_script#configuration

`~/.config/mpv/script-opts`

**Comment by SonaliBendre** [comment]
Mpv in crashing at launch in Windows 11 due to dependencies

**Comment by open-dynaMIX** [comment]
Could you please clearly state your request or question? You can configure the webui in a `webui.conf` file, the main mpv config file or the commnad line. This is a feature of mpv, not from the webui.

The webui doesn't provide a config file itself. It just [reads the values provided by mpv](https://github.com/open-dynaMIX/simple-mpv-webui/blob/main/main.lua#L20).

> Mpv in crashing at launch in Windows 11 due to dependencies

This belongs to #385 and as you correctly wrote, is a problem with the dependencies you seem to have incorrectly installed.

If there is a bug in the webui that leads to an error, mpv will still run, but the webui will not be available. If mpv crashes, it most likely means, that you messed up your installation/dependencies. There's nothing I can do about it.

I can offer to take a loot, if you paste the output of mpv, when run from command line. But you probably have better chances asking for help [here](https://github.com/57op/simple-mpv-webui-windows-libs).
Windows support is best-effort. I don't use any windows system, therefore I can't (don't want to) really test things. But PRs are welcome.

**Comment by SonaliBendre** [comment]
https://github.com/57op/simple-mpv-webui-windows-libs/issues/4

**Comment by 57op** [comment]
@SonaliBendre i've updated the DLLs for newer mpv builds, you can find a new release in the repo page.
now you should be able to use this extension without issues

**Comment by open-dynaMIX** [comment]
Thanks a lot @57op !
