### ISSUE TITLE
[Windows] calling 'send' on bad self (tcp{client} expected)

### ISSUE THREAD

**Issue by SonaliBendre** [open-dynaMIX/simple-mpv-webui#399]
Path in Windows doesn't work either its COllection or httpasswd. 

Frequently crashing i n Windows just after clicking any button in web-ui

**Comment by open-dynaMIX** [comment]
What output do you get on a crash?

**Comment by alexpandain** [comment]
this issue can be fixed by installing https://github.com/dyphire/mpv-winbuild/releases
