### ISSUE TITLE
collections have been defined but the list is empty.

### ISSUE THREAD

**Issue by dream7180** [open-dynaMIX/simple-mpv-webui#405]
collections have been defined but the list is empty. Below is the output. What can I do  to detect my video directors and files, anything missing? I include the path to main.lua: collections = "/nasd1/Video"

![image](https://user-images.githubusercontent.com/18242221/184524743-f30f0cd3-cb3a-41bd-b48e-e16d19e7dfae.png)

**Comment by dream7180** [comment]
The setting seems OK, see browser output below. But the file browsing of webui is empty. What is wrong? Thank you!

![image](https://user-images.githubusercontent.com/18242221/184533318-1425d8d0-9910-4bb7-9507-4c0adadfa3ed.png)

![image](https://user-images.githubusercontent.com/18242221/184533337-21f87b08-245c-42db-a346-bd2ca4da1562.png)

**Comment by open-dynaMIX** [comment]
Hey @dream7180 

To me it seems like the webui is working correctly, but you have not loaded any files. The empty list you see is the empty playlist and has nothing to do with any configured collections.

The collections feature is not yet available through the webui, just the necessary API calls are implemented. Your first screenshot shows, that this is also working correctly. Please try opening some media files with MPV and then open the webui again.

BTW: There is no need to edit `main.lua`. Just configure your settings as explained in the [README.md](https://github.com/open-dynaMIX/simple-mpv-webui#options). This makes it easy to pull new changes from git.

**Comment by dream7180** [comment]
Thanks. Hope the file browsing feature can be implemented. It is essential for me as my computer has no desktop UI and no keyboard & mouse that used as NAS+HTPC connected to TV. I am seeking for controlling MPV through mobile phone totally independant. Husudosu's mpv-remote-node with app is great but there is problem in my linux system. Anyway, thank you and look forward to the update of your webui.

**Comment by open-dynaMIX** [comment]
Opening file through the webui is tracked in #343.
