### ISSUE TITLE
do we have `web-ui.conf` ?

### ISSUE THREAD

**Issue by omaru-ok** [open-dynaMIX/simple-mpv-webui#423]
why there is no `web-ui.conf`  which goes to `/config/sciprt-opts/webui.conf`
i mean i read [options](https://github.com/open-dynaMIX/simple-mpv-webui#options) but not seem to have  configuration file?
am i wrong?

also the option `webui-`  threw me this error 🙏 i dont know what i did wrong
![image](https://user-images.githubusercontent.com/108952834/199227080-0d444325-bebf-43ab-a299-aa4d0a87a8c7.png)

if i used cli parameters like `--webui-osd_logging=yes` got this error 
![image](https://user-images.githubusercontent.com/108952834/199227302-23e02373-2e3b-480c-8452-ace94fbbabf8.png)

**Comment by open-dynaMIX** [comment]
In order to make this more clear for all users, I've added a [paragraph about this](https://github.com/open-dynaMIX/simple-mpv-webui#setting-options) to the README.

**Comment by omaru-ok** [comment]
:O  this is soo good now
