### ISSUE TITLE
FIX readme.md  / wrong options

### ISSUE THREAD

**Issue by omaru-ok** [open-dynaMIX/simple-mpv-webui#449]
![image](https://user-images.githubusercontent.com/108952834/214023404-6d97ab9f-ad6f-41f1-ad41-686bcef3a3ed.png)

i just copied the [OPtions](https://github.com/open-dynaMIX/simple-mpv-webui#options) merely all 

and got a error .

**Comment by open-dynaMIX** [comment]
Please refer to [this section](https://github.com/open-dynaMIX/simple-mpv-webui#setting-options) of the README for information about how to set options.

If you use a dedicated `webui.conf`-file, you have to omit the `webui-`-prefix: `webui-ipv4` -> `ipv4`.

**Comment by omaru-ok** [comment]
> `webui-`-prefix: `webui-ipv4` -> `ipv4`.

that is the the thing i had forgotten  THX !!
