### ISSUE TITLE
access from phone? / using another device browser 

### ISSUE THREAD

**Issue by omaru-ok** [open-dynaMIX/simple-mpv-webui#450]
i like the idea of using through web  , 
but i am not able to understand how can i use it with my android device? 
 i mean i use webui on PC which stream to TV . which i need to control from MOBILE  HOWWW?

**Comment by open-dynaMIX** [comment]
You need to know the IP of your host, where the webui is running. Then you can access it from the browser on your mobile: `http://YOUR_IP:8080`. For this to work you must make sure that no firewall restricts port 8080.

**Comment by omaru-ok** [comment]
> You need to know the IP `http://YOUR_IP:8080`
okay i have figured it out 
here what do do ! 
`guessing webui setup is fully done ` 
1.  find the IP of your netwrok [LAN] for this go to [setting](ms-settings:network-wifi?activationSource=SMC-IA-4026518) > WIFi> properties > IPv4 address> 
2. coy that ipv4 > paste it on phone then add colon `:`  after the pot ur using like this 
3. `192.1XX1.XX:8080`
ease as breeze thx for the help
