### ISSUE TITLE
Feature Request: Add/Modify Tiles

### ISSUE THREAD

**Issue by purrpurrn** [open-dynaMIX/simple-mpv-webui#483]
# Description
Users should have the function to remove, modify, changing the order, size of the tile and add new tiles.

## Examples
**Example 1:** I wanna change the name of the tile `*Slower*` to -0.5% and change the color to purple.
**Example 2:** Adding a tile to open the Info menu `(Shift+I)
**Example 3:** Adding a tile to activate/deactivate debanding

**Comment by open-dynaMIX** [comment]
Sorry for the late response. I don't have the time to put too much work into this project at the moment, aside from keeping it stable.

The customization you're asking for is not gonna happen. The frontend is far from perfect right now and would probably profit from a full rewrite, that also could incorporate more customization options.

## Workaround

Exactly for your usecase, there is the [static_dir](https://github.com/open-dynaMIX/simple-mpv-webui?tab=readme-ov-file#static_dir)-option. You can use it to serve an alternative frontend. As a starting point, you can make a copy of the current frontend and modify it to your needs/taste.
