### ISSUE TITLE
Cannot get status when playing streamed file

### ISSUE THREAD

**Issue by sohsatoh** [open-dynaMIX/simple-mpv-webui#5]
Cannot get /apt/status when playing streamed file such as https://c5.prod.playlists.ihrhls.com/1469/playlist.m3u8

**Error**
Error: Not ready to handle requests.

**Comment by open-dynaMIX** [comment]
I assume you mean `/api/status` as `/apt/status` will return a 404.

I can't reproduce this issue. The status endpoint works for me with this playlist. The error you are geting indicates that there was a problem to fetch (parts of) the status information from mpv.

I've enabled some more logging. Please test again with latest master and check the output of mpv.

**Comment by sohsatoh** [comment]
Hi,
I found it is because that the distributed mpv on raspberry pi is ver 0.23.
I manually built mpv, and this works on v0.29.
Thanks.
