### ISSUE TITLE
Crash of mpv v0.38.0

### ISSUE THREAD

**Issue by Lc4B** [open-dynaMIX/simple-mpv-webui#504]
I'm on windows 10, and I updated mpv from the latest master version of v37 (14-04) to stable v38 (20-04) and now after a short time when I start mpv there is some loading and it closes, I went to remove the scripts one by one and it turns out that this is what causes it to crash. I don't know what may have been changed this week but if I remove this script everything works perfectly, can someone check?

this is the log file with the base v38 without settings and with only this script loaded: [v38.log](https://github.com/open-dynaMIX/simple-mpv-webui/files/15048983/v38.log)

**Comment by redomCL** [comment]
我有同样问题，在浏览器上使用ip进行网页访问可以加速复现这个问题
I have the same issue, using IP for web page in browser access can quickly recurrence this issue

**Comment by JiLleON** [comment]
Same issue

**Comment by dyphire** [comment]
Just because the luajit and luasocket you are using [there](https://github.com/57op/simple-mpv-webui-windows-libs) are outdated and you need to update them.

They can be downloaded in my release: https://github.com/dyphire/mpv-winbuild/releases

**Comment by Lc4B** [comment]
> Just because the luajit and luasocket you are using [there](https://github.com/57op/simple-mpv-webui-windows-libs) are outdated and you need to update them.
> 
> They can be downloaded in my release: https://github.com/dyphire/mpv-winbuild/releases

yes, you're right, with your luasocket the latest master version of mpv works fine for me. Thank you!
